name: Deploy on Push

on:
  push:
    branches:
      - '*' # Escucha cambios en cualquier rama

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
          root-password: ${{ secrets.MYSQL_ROOT_PASSWORD }}

      - name: Run migration
        run: |
          mysql -h localhost -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} my_database < ./migrations/migration.sql